---
title: "CSE7305c CUTe"
author: "Amar Rao"
date: "December 21, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

rm(list = ls(all = TRUE))

#load all required libraries
require(tidyverse)
require(e1071)
require(caret)
require(stats)
require(knitr)

```


Read in the data set

```{r}
setwd('~/datasets/CSE7302c_CUTe')

train_data <- read.csv('train.csv')
summary(train_data)
```
```{r}
str(train_data)
```

```{r}
train_data$target <- as.factor(train_data$target)
str(train_data)
```

```{r}
max(train_data$ID)
#we don't need the id column.
train_data$ID <- NULL
str(train_data)
```

```{r}
sum(is.na(train_data))

sort(colSums(is.na(train_data)), decreasing=TRUE)
```

```{r}
summary(train_data$Attr37)

```

```{r}
boxplot(train_data$Attr37)
```

#imputing Attr37 makes no sense as half the table is empty and as the boxplot shows, there're outliers that are several orders of magnitude larger than the mean and median. 

```{r}

```

